python from the shell slides
uc-python/python-training-cincinnati-insurance pull request #38
Opened 2023-01-30 19:15 UTC by cunningjames

Closes #21.

This is a fairly straight port of Ethan's slides from the intermediate class, switched from Jupyter to VS Code. It's good material to have, though I wonder if some of the class will find it a bit basic. I'm happy to revisit if you guys think it's necessary.

From a technical perspective, I'm not sure whether or not they'll be able to use ipython easily, particularly the Windows users, but we can deal with that as necessary.

2023-01-30 20:49 UTC, augustopher requested changes
Also need to add the usual "Questions" slide at the end.

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "</font>\n",
Update to a `h3` header.

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "</div>"
Remove the custom formatting and just bold it.

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "</font>\n",
Convert to a `h3` header.

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "Open a new text file in Jupyter and type the same code as before:\n",
```suggestion
    "Open a new text file in VS Code and type the same code as before:\n",
```

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "</font>\n",
Convert to `h3` header.

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "#### Graphics"
```suggestion
    "### Graphics"
```

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "#### Automatic Printing of Output"
```suggestion
    "### Automatic Printing of Output"
```

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "#### Cell Magics and `?`"
```suggestion
    "### Cell Magics and `?`"
```

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +     "slide_type": "slide"
To match the flow of this section, this should build into the title from above:

```suggestion
     "slide_type": "fragment"
```

2023-01-30 20:49 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "#### Batching Code"
```suggestion
    "### Batching Code"
```

2023-01-30 21:29 UTC, cunningjames commented
Thanks, @augustopher. I think I've addressed all your comments.

2023-01-30 21:32 UTC, augustopher commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "</font>\n",
Guess I missed one here.

2023-01-30 21:34 UTC, cunningjames commented on notebooks/12-Python_from_the_Shell.ipynb
> +    "</font>\n",
Fixed, thanks!

2023-01-30 21:35 UTC, augustopher approved these changes

2023-01-31 04:18 UTC, eswan18 commented
FYI – feel free to merge these with just one approval. I have work events most of the day tomorrow and into the evening, and then again the next day, so I won't be able to review all these.

I'll do a once-over of all of the material later in the week.

2023-01-31 13:09 UTC, merged